spring.application.name=SugarCaneLabour
spring.profiles.active=${ENV:local}

#swagger
#springdoc.api-docs.path=/v3/api-docs
#springdoc.swagger-ui.path=/swagger-ui
#springdoc.swagger-ui.operations-sorter=alpha
#springdoc.swagger-ui.tags-sorter=alpha
#
#
#springdoc.swagger-ui.default-models-expand-depth=-1   
#springdoc.swagger-ui.default-model-expand-depth=-1      
#springdoc.swagger-ui.doc-expansion=none  

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

#Batch Processing
# Adjust batch size based on system performance
spring.jpa.properties.hibernate.jdbc.batch_size=1000
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true


