# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://147.79.70.77:5432/sugarcane_labour
spring.datasource.username=sugarcane_user
spring.datasource.password=sclm@123
spring.datasource.driver-class-name=org.postgresql.Driver

#

#logging.level.org.hibernate=DEBUG
#logging.level.org.springframework.jdbc=DEBUG


spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Server Configuration

server.port=8081

# Mail Configuration
spring.mail.host = smtp.gmail.com
spring.mail.port = 587
spring.mail.properties.mail.smtp.starttls.enable = true
spring.mail.username = vaishubakal883@gmail.com
spring.mail.password = mdhl puag gysv lwrj
spring.mail.properties.mail.smtp.starttls.required = true

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
spring.mail.properties.mail.smtp.startssl.enable=true

# HikariCP Configuration
spring.datasource.hikari.connection-timeout=30000  
spring.datasource.hikari.maximum-pool-size=5   
spring.datasource.hikari.minimum-idle=10       
spring.datasource.hikari.idle-timeout=3000      
spring.datasource.hikari.max-lifetime=900000           
spring.datasource.hikari.leak-detection-threshold=10000 

# Swagger Configuration
swagger.title=SugarCane Labor REST API [DEVELOPMENT]

#dev JWT Keys
jwt.privateKey.path=/home/dhammuser/private-key.pem
jwt.publicKey.path=/home/dhammuser/public-key.pem
#local JWT Keys
#jwt.privateKey.path=C:/Sajid/Projects/home/streesaktiuser/private-key.pem
#jwt.publicKey.path=C:/Sajid/Projects/home/streesaktiuser/public-key.pem

#Config
https.server.url=https://ustodsurvey.in
http.server.url=http://ustodsurvey.in


#file.upload.dir=E://New folder//Projects//filesUploadDir
#UPLOAD_DIR_LABOR=E:/New folder/Projects/filesUploadDir

file.upload.dir=/var/www/uploads/UTS/profileImage/
UPLOAD_DIR_LABOR=E:/New folder/Projects/filesUploadDir

#redis config
spring.redis.host=127.0.0.1
spring.redis.port=6379
spring.redis.password=ust@dk@@mg@r
